name = "ddns-cf-worker"
main = "build/index.js"
compatibility_date = "2025-09-21"

[build]
command = "cargo install -q worker-build && worker-build --release"

[assets]
directory = "./dist/"
run_worker_first = [ "/update" ]

[observability]
enabled = true

[vars]
DDNS_DOMAIN_SUFFIX = "ddns.sorz.org"
DDNS_RECORD_TTL = "180"
# DDNS_CF_API_TOKEN=abcdefg-1234567
# DDNS_CF_ZONE_ID=aabbccddeeff1122

[[routes]]
pattern = "ddns.sorz.org"
custom_domain = true

[[kv_namespaces]]
binding = "ddns_host_password"
id = "31cad14e9d0243aea72e964a1fc5a913"
